version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mythyroots_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mythyroots
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ../sql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

volumes:
  db_data:
